export default [
    {
        title:'主页',
        icon:'HomeIcon',
        path:'/',
    },{
        title:'定时公告管理',
        icon:'FileIcon',
        path:'',
        subItems:[
            {
                title:'公告管理',
                icon:'FileIcon',
                path:'/announcement',
            },{
                title:'模板管理',
                icon:'FileIcon',
                path:'/announcement/template',
            }
        ]
    },{
        title:'用户管理',
        icon:'FileIcon',
        path:'/admin/user',
        role:"admin"
    },{
        title:'用户设置',
        icon:'FileIcon',
        path:'/config',
    },{
        title:'关于我们',
        icon:'FileIcon',
        path:'/about',
    }
]