export default [
    {
        title:'主页',
        icon:'HomeIcon',
        path:'/home',
    },{
        title:'定时公告管理',
        icon:'FileIcon',
        path:'',
        subItems:[
            {
                title:'公告管理',
                icon:'FileIcon',
                path:'/announcement'
            },{
                title:'模板管理',
                icon:'FileIcon',
                path:'/announcement/template'
            }
        ]
    },{
        title:'关于我们',
        icon:'FileIcon',
        path:'/about'
    }
]